### ISSUE TITLE
Not an issue...this is just...awesome! :-)

### ISSUE THREAD

**Issue by rchrdnsh** [tobx/music-mode-wheels#1]
Just love what you did here...I'm trying to figure out how to do much of this myself (making svg circles to convey musical information) Thank you very much for making this!

XD

**Comment by rchrdnsh** [comment]
I will close it as it's not actually an issue :-)

**Comment by tobx** [comment]
Nice to hear :) I learned it by starting this project. There are some details that are probably not easy to understand, because I calculated it on paper, did not document it and just wrote down the code.

If you have time to look at my code, the best starting point are probably the files `PianoWheel.svelte` (the inner piano key wheel) and `ModeWheel.svelte` (the outer mode wheel) in here:
https://github.com/tobx/music-mode-wheels/tree/main/src/components/scale-wheel

Since you have Svelte experience, there is almost no difference between manipulating HTML and SVG.

**Comment by rchrdnsh** [comment]
Thank you for your reply...yeah, been trying to look through it, but it is admittedly quite a lot to take in...I've gotten a segmented svg circle going on my own by forking an observableHQ example...now I'm trying to figure out how to put text in each circle segment...failing pretty miserably at this point, however 🤣

Check it out! 😁

https://svelte.dev/repl/554dfd9a6f344c79a7f0239133b24639?version=3.38.2

...just don't understand how svg works well enough yet, it would seem 😕

**Comment by rchrdnsh** [comment]
This is the segmented circle I forked for mine...it's quite nice :-)

https://observablehq.com/@haakenlid/svg-circle

**Comment by tobx** [comment]
It looks like you gotten already quite far. I love that you used `chroma.lch` for the colors :)

By shortly looking over your code I noticed two things:

1. You might save some thinking energy by just creating the whole circle around point 0,0 (so only the lower right corner is visible) and put it in a SVG group (`<g>`) and use transform/translate to move the whole thing to where you want to have it. So do not translate every part of the circle to 50%, 50%, but translate the whole circle in a group to 50%, 50%. E.g. `<g transform="translate(50%, 50%)"><AllTheCircleElements /></g>`.


2. Same for the text: you should probably create the whole segment with the text on the top of the circle (horizontal) and then put everything in a group and rotate that whole group with transform/rotate.

By creating the music wheels I realized at one point, that you should transform as late as possible (or speaking SVG: as parent as possible).

I hope you did not do it that way already and I just overlooked it :)

**Comment by rchrdnsh** [comment]
lol, the chroma thing was by the person who made that observable, not me...i'm just forking it...badly...

but yeah, been slowly learning the similar things as you, but exploring other options as well...anyway, starting to get somewhere!

https://svelte.dev/repl/f18750780a1f483d9404b4ce0b435f5a?version=3.38.2

XD

**Comment by tobx** [comment]
Looking good. Of course the horizontal text requires more math to find the positions than what I did :)
